version: 2.1
jobs:
  Client:
    docker:
      image: circleci/node:12
    steps:
      - checkout
      - run:
          - name: npm install for client
          - command: cd client && npm install
      - run:
          - name: Run client tests
          - command: cd client && npm run test
workflows:
  Build and Test:
    jobs:
      - Client
