# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd client
        npm ci
        npm test
    - name: running server test
      env:
        PORT: ${{ secrets.PORT }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASS: ${{ secrets.MONGO_PASS }}
        MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
      run: |
        cd server
        npm ci
        PORT=$PORT NODE_ENV=$NODE_ENV MONGO_DB=$MONGO_DB MONGO_USER=$MONGO_USER MONGO_PASS=$MONGO_PASS MONGO_CLUSTER=$MONGO_CLUSTER npm server-test:CI
        