# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd client
          npm ci
          npm test
      - run: |
          cd server
          npm ci
      - name: Running Server and test
        env:
          G_PORT: ${{ secrets.PORT }}
          G_NODE_ENV: ${{ secrets.NODE_ENV }}
          G_MONGO_DB: ${{ secrets.MONGO_DB }}
          G_MONGO_USER: ${{ secrets.MONGO_USER }}
          G_MONGO_PASS: ${{ secrets.MONGO_PASS }}
          G_MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
        run: |
          cd server
          echo $G_PORT
          npm run server-test:CI
